# Generated by Django 4.0.1 on 2022-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_room',
            name='remarks',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
