# Generated by Django 4.0.2 on 2022-04-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Tenant',
        ),
    ]
