# Generated by Django 4.0.2 on 2022-04-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
