# Generated by Django 4.0.2 on 2022-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misc', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='user'),
        ),
    ]
